### ISSUE TITLE
ndx parse

### ISSUE THREAD

**Issue by kaileung** [WayneD/rsync#100]
in io.c:2178:write_ndx()
`diff = ndx - prev_positive` or `diff = ndx - prev_negative`

but in read_ndx()
if the packet is start with `0xFF 0xFE (bit | 0x80) xxxxx`, the result number is 
`num = IVAL(b, 0)`, but i think is  `num = IVAL(b, 0) + *prev_ptr;`

i know if get `0xff fe ff ff ff ff`, translate reulst is `0x7f ff ff ff`, is max of int32. but if is first write_ndx() got` ndx = 0x7f ff ff ff `, it work correct?

**Comment by WayneD** [comment]
In the write_ndx() code, if we have to send a 4-byte value after the prefix bytes, we send it based on the full ndx value, not the diff.  Thus, the code in read_ndx() is correct when it is processing a sequence that starts with FF + FE + a high-bit set in the next byte (there is no use made of the prev value in the reading of the number because it wasn't used in the storing of the number). The sent ndx value is never larger than 0x7FFFFFFF.

So, to be clear, the code sends one of:

- a 1-byte end-of list == 00
- a 1-byte positive offset of 01 .. FD (the most common case)
- a 3-byte positive offset of FE + 0000 .. 7FFF
- a 5-byte full ndx positive value of FE + (high-bit forced on) 80000000 .. FFFFFFFF
- a negative ndx value that always starts with a FF and is followed by either the 1, 3, or 5-byte encodings listed above (not including the end of list choice) with the ndx value encoded as a positive value.

**Comment by kaileung** [comment]
ohhh.....i have a mistake when send  4 byte ndx...thx~
