### ISSUE TITLE
How to check the actual checksum algorithms used

### ISSUE THREAD

**Issue by timarupopoka** [WayneD/rsync#101]
How can I check the checksum algorithm that was actually used as a result of the negotiation?
I would like to know if the `--cc` option is definitely applied or what the consequences would be if `--cc` was not used.
I tried the `-v` option, but it didn't show up.

**Comment by WayneD** [comment]
There is no question what checksum algorithm is used when `--cc` is specified, since it fails if it can't use that algorithm. That said, you can always see what rsync is doing by specifying `--debug=nstr` (where nstr is short for negotiation strings) -- it always outputs the checksum info.  And for even more info you could use `{-M,}--debug=nstr5` to tell both sides to be very chatty about the nstr info.

**Comment by timarupopoka** [comment]
> There is no question what checksum algorithm is used when --cc is specified, since it fails if it can't use that algorithm.

This is the preferred behavior for me.
And your advice has allowed me to observe the negotiation. Thank you!
