### ISSUE TITLE
Incorporate --copy-devices into main codebase

### ISSUE THREAD

**Issue by kucharskim** [WayneD/rsync#121]
RedHat and Fedora seem to have `--copy-devices` for many years and the patch is present / maintained at https://git.samba.org/rsync-patches.git, so why not merge it and maintain it as part of the rsync source code? I find feature itself useful and relied on it over the years.

**Comment by WayneD** [comment]
I've implemented this option in a much better way for inclusion in 3.2.4.

I hadn't merged it before because the patch wasn't written in the right way (and because I took far to long to get around to fixing that).  It's sad that the RedHat folks included it, as it made my final version more complicated having to deal with a sender that accepts `--copy-devices` but doesn't do what the sender is now supposed to do.  I did update the patch in the rsync-patches repo prior to merging it with a version that they should be able to adapt in place of their old patch.
