### ISSUE TITLE
net/rsync --crtimes, -N: preserve creation/birth time is not supported

### ISSUE THREAD

**Issue by ghost** [WayneD/rsync#166]
@WayneD 

Based on this report in FreeBSD Bugzilla.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254354

> Here you can see that FreeBSD generally supports crtime/btime see the stat command.
> 
> 
> stat -f "Access (atime): %Sa%nModify (mtime): %Sm%nChange (ctime): %Sc%nBirth  (crtime/btime): %SB" /video.mkv
> 
> Access (atime): Nov 22 16:07:46 2018 
> Modify (mtime): Nov 22 16:07:46 2018
> Change (ctime): Nov 22 16:07:46 2018
> Birth  (crtime/btime): Nov 01 01:19:02 2016
> 
> 
> 
> If the user uses rsync (3.2.3) to preserve the crtimes with --crtimes or -N  for directories and files, it does not work. It says in the terminal that it is not supported.

I can also reproduce this problem on other BSD systems, such as OpenBSD (6.8) and NetBSD (9.1).

It is generally known that all BSD family and other Unix systems have supported Birth time (`btime`) for files + directories for ages.

This means that a patch in rsync should add that it generally fixes this problem. So that all BSD systems and other Unix  systems can use it immediately.

**Comment by WayneD** [comment]
BSD doesn't have support for setting the birth value to an arbitrary value on an existing file, so it's not supported in rsync.

**Comment by jtommi** [comment]
@WayneD I get the same on Debian and Fedora, rsync 3.2.3

**Comment by Yetoo1** [comment]
@WayneD Please reopen this, I also experience this issue with rsync 3.2.3 on Fedora.

**Comment by WayneMDB** [comment]
This issue is about crtimes on FreeBSD, which doesn't have full crtimes support (it only sets crtime at file creation and when the mtime moves prior to the creation time). The patch you cited is for OS X, which rsync already supports just fine without any patches.  Linux doesn't support crtimes in general, but if someone has a portable extension patch feel free to submit it.

**Comment by WayneD** [comment]
This issue is about crtimes on FreeBSD, which doesn't have full crtimes support (it only sets crtime at file creation and when the mtime moves prior to the creation time). The patch you cited is for OS X, which rsync already supports just fine without any patches. Linux doesn't support crtimes in general, but if someone has a portable extension patch feel free to submit it.

**Comment by Perdu** [comment]
Re-opening: I still have this issue on Arch Linux with version 3.2.7

**Comment by githubmyname** [comment]
https://www.linuxquestions.org/questions/linux-newbie-8/how-do-i-preserve-crtime-creation-birth-time-when-copying-from-windows-ntfs-to-linux-ext4-4175625229/
Has anyone solved this problem? Keep creation time in linux
