### ISSUE TITLE
rsync: This rsync does not support --atimes (-U)

### ISSUE THREAD

**Issue by filIAI** [WayneD/rsync#226]
1) 
```
sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

2) 
```
mount | column -t
/dev/disk2s1    on         /System/Volumes/Data     (apfs,                     local,           journaled,    nobrowse)
```

3)
```
rsync -U
rsync: This rsync does not support --atimes (-U)
rsync error: syntax or usage error (code 1) at main.c(1768) [client=v3.2.3-74-g592c6bc3]
```

**Comment by WayneD** [comment]
Apple builds must have getattrlist() for rsync to be able to compile-in that support.

**Comment by filIAI** [comment]
> 
> 
> MacOS doesn't support that.
According to Apple's documentation, macOS supports it. What is not working on your site?

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getattrlist.2.html

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setattrlist.2.html

> ATTR_CMN_ACCTIME

**Comment by WayneD** [comment]
Sorry for the confusion.  I recall that `--atimes` got disabled earlier due to the code not working on macOS, but since I don't often have a good ways to test things on macOS, I didn't have a good way to figure out what was going on (and nobody contributed a patch).  However, I've just managed to do some testing on a super old mac, and that let me trace down the issue and check in a fix.

**Comment by AIAIiI** [comment]
@WayneD 
https://github.com/WayneD/rsync/commit/78b5bc66290aa24c69966110421a005faa37a625

Good work, thank you, it worked. If use `rsync -tU`

I have done some tests now and there are still 2 functions missing that rsync does not support yet.

When these options are used, `--atimes` for the target is set to the current time and is not preserved by the source.

```
rsync -U 123.txt new

rsync -UN 123.txt new
```
