### ISSUE TITLE
--back --delete with deleted sub-directory and files within it in source

### ISSUE THREAD

**Issue by TooChaos** [WayneD/rsync#258]
Hello WayneD

I observe the following behaviour of rsync (version 3.1.3  protocol version 31) and think you might be interested.

I start with `source` having the following struct where the destination is identical
`source/
source/d1/
source/d1/1
`
Then I remove the file `1` and the sub-directory `d1` in the `source`
I run `rsync` to sync source and destination as follows
`rsync -auvhr --delete  --backup --suffix="bak-`date +%F%H%M%S`"  source target`
I got the following output

`sending incremental file list`
`deleting source/d1/1`
`cannot delete non-empty directory: source/d1`
`sent 71 bytes  received 77 bytes  296.00 bytes/sec`
`total size is 0  speedup is 0.00`

Then I got in the destination
`target/source:`
`target/source/d1:`
`target/source/d1/1bak-2021-11-20111534`

This is out of my expectation as I would like to have `d1` becomes `d1-bak....` in the destination. Do you think this is a bug or what I expected shall be an enhancement? 

Also, if I do it slightly differently, i.e. after I remove file `1` I run `rsync` immediately, I get expected result:
`target/source/d1/1bak-2021-11-20113527`

Then I remove `d1` and run `rsync` again. I would have end up had 
`target/source/d1/1bak-2021-11-20113527bak-2021-11-20113603`
in the destination. Looks like the `rsync` mistaken the "backup" file as the "current" file.

The second case looks more like a bug. Thank you for your time!

**Comment by WayneD** [comment]
Rsync is letting you know that the source/d1 dir has backup names inside it, so it can't remove it.  Rsync only does backups of files, not backup of dirs, so it doesn't try to move old dirs around.  As such, it is usually better to use a `--backup-dir` option to put your backup files into a separate backup hierarchy instead of intermixing the backup files into the destination directory, as rsync handles that situation in a better manner.
