### ISSUE TITLE
chown leads to "No matches for wildcard" in combination with fish shell

### ISSUE THREAD

**Issue by brejoc** [WayneD/rsync#272]
When using the `--chown` flag with rsync on a target server that has fish shell as the default for the user, rsync errors out with a "No matches for wildcard". fish always eagerly tries to expand wildcards, which is not possible in this case.

```
$ rsync -avz --chown root:root . user@example.com.com:/srv/html/example.com/.
root@example.com's password: 
fish: No matches for wildcard “--usermap=*:root”. See `help expand`.
rsync --server -vlogDtprze.iLsfxCIvu --usermap=*:root --groupmap=*:root . /srv/html/example.com/.
                                     ^
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
```

rsync version: `rsync  version 3.2.3  protocol version 31`

Wouldn't it be possible to escape the asterisk or use quotes in this case?

**Comment by WayneD** [comment]
Use `--protect-args` option (`-s`) or `export RSYNC_PROTECT_ARGS=1` in your environment or compile rsync after using `./configure --with-protected-args`.  At some point this will become the default.  Hmm, maybe I'll make it the default for 3.2.4.

**Comment by WayneD** [comment]
I decided that making `--protect-args` the default was a little too intrusive since it forces everyone using rrsync (the restricted rsync script) to start having to specify `--no-s`.  Instead, the latest rsync now auto-escapes various args for you (using backslashes), so the `--protect-args` option is now an alternate safety method that has the added benefit of doing `--iconv` conversions on filenames.
