### ISSUE TITLE
3.2.0 Fails to build on Alpine Linux

### ISSUE THREAD

**Issue by fazalmajid** [WayneD/rsync#29]
```
g++ -g -O2 -fno-exceptions -fno-rtti -O2 -I/usr/local/include -I/usr/local/ssl/include -UHAVE_SIMD -c -o simd-checksum-x86_64.o ./simd-checksum-x86_64.cpp
./simd-checksum-x86_64.cpp: In function 'uint32_t get_checksum1_cpp(char*, int32_t)':
./simd-checksum-x86_64.cpp:88:52: error: multiversioning needs ifunc which is not supported on this target
   88 | __attribute__ ((target("default"))) MVSTATIC int32 get_checksum1_avx2_6(schar* buf, int32 len, int32 i, uint32* ps1, uint32* ps2) { return i; }
      |                                                    ^~~~~~~~~~~~~~~~~~~~
./simd-checksum-x86_64.cpp:474:1: error: use of multiversioned function without a default
  474 | }
      | ^
./simd-checksum-x86_64.cpp:89:52: error: multiversioning needs ifunc which is not supported on this target
   89 | __attribute__ ((target("default"))) MVSTATIC int32 get_checksum1_ssse3_32(schar* buf, int32 len, int32 i, uint32* ps1, uint32* ps2) { return i; }
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~
./simd-checksum-x86_64.cpp:474:1: error: use of multiversioned function without a default
  474 | }
      | ^
gmake: *** [Makefile:135: simd-checksum-x86_64.o] Error 1
```

I'm guessing that's because `ifunc` is a glibc feature, which would not work on a Linux that uses non-GNU libc like Alpine with musl libc.

The same error occurs on SmartOS.

**Comment by WayneD** [comment]
You can use --disable-simd configure option.

**Comment by fazalmajid** [comment]
It also fails on OS X 10.14 Mojave, even if you remove `HAVE_SIMD`. The error is a bit different:

```
gcc -c -o lib/md5-asm-x86_64.o ./lib/md5-asm-x86_64.s
./lib/md5-asm-x86_64.s:31:1: error: unknown directive
.type md5_process_asm,@function
^
./lib/md5-asm-x86_64.s:693:1: error: unknown directive
.size md5_process_asm,.L_md5_process_asm_end-md5_process_asm
^
gmake: *** [Makefile:138: lib/md5-asm-x86_64.o] Error 1
```

**Comment by WayneD** [comment]
Don't remove HAVE_SIMD, re-run configure with --disable-simd.

**Comment by fazalmajid** [comment]
OK, thanks!

I will wait for the next release (3.2.1?) to rebuild on Darwin.

**Comment by WayneD** [comment]
It would be helpful if you'd test the latest master branch, if possible.

I've changed the configure check to do a compile test and not try to use SIMD if it fails.

**Comment by WayneD** [comment]
It would also be nice if some of the SIMD contributers would also give the latest configure.ac setup a try and see what you think. My latest version will give folks w/o a c++ a pass (it won't try to force them to supply a compiler) but I think that's OK as it should also not hassle them if their compiler can't build the test source. Thanks!

@Chainfire @benrubson @eworm-de @hhoffstaette

**Comment by fazalmajid** [comment]
OS X Mojave compile still fail in the master branch if you don't supply `--without-simd`. It does build properly with `--without-simd`. Perhaps the SIMD configure test should also verify libc is glibc, or the code be changed not to rely on multiversioning.

**Comment by WayneD** [comment]
A glibc test is a non-starter because we also work fine on BSD. We really just need to get the configure test to fail if it's not going to work. I already verified that it properly disables simd on Alpine.  I'm adding an echo in the build sequence to make sure that folks know about `--disable-simd` should they manage to get a successful test but an unsuccessful build.

**Comment by WayneD** [comment]
I made the configure test now actually link & run the program, not just compile it. Hopefully that will make your Mohave setup ignore the simd code.

**Comment by debohman** [comment]
Yes, I have run into the clang++ crash when compiling ./simd-checksum-x86_64.cpp. I am using the public llvm-10.0.0 release.

If you remove the -g or the -O2 from the compile command, it compiles successfully. As a workaround invoke ./configure as such to remove the -g:

`CXXFLAGS= ./configure`

I plan to file a bug against llvm/clang++ about this once they give me a bug reporting account.

**Comment by WayneD** [comment]
My latest commit removes the `-g` option from the CXXFLAGS, since it's only the one file (and if we need to debug it, we can manually add it back).  Feel free to try out the master branch and see if that builds w/o error for you.

**Comment by debohman** [comment]
The llvm/clang++ crash is clearly their bug, because it should never crash, regardless of what you feed to it. I am saving the preprocessed input and the invocation information, and I will file a bug with them as soon as they give me an account.

I will try out the top of tree shortly.

**Comment by debohman** [comment]
With the top of tree, the simd test for configure crashes llvm/clang++ 10.0.0.

I worked around it by supplying `CXXFLAGS=-O2` on the configure line. My full line is now:

`CPPFLAGS=-I/usr/local/include CXXFLAGS=-O2 LDFLAGS=-L/usr/local/lib ./configure`

The problem is that now, it does not find SIMD at runtime judging with rsync --version. I am using Westmere-EP processors, which have SSE4.2.

**Comment by WayneD** [comment]
Oh yeah, I meant to elide the `-g` prior to the test. I've moved it.

One thing to keep in mind about the latest `--version-` output is that you need to use `-VV` to see SIMD/no SIMD (and now ASM/no ASM) in the list (and they show up early in the list).  Since they're just optimizations and not user-facing features, I figure they're not that relevant to the average user.

**Comment by debohman** [comment]
Looks good now!

**Comment by Chainfire** [comment]
Re: crash

I've seen LLVM crashes during development as well, which ended up being fixed by removing all static/inline modifiers. The issue may be that `more_testing()` is declared inline.

Re: ifuncs

The code will not be re-done without ifuncs. This moves the burden of CPU detection and dispatching to the code, which has many pitfalls by itself.

Re: configure.ac

I'll give the new code a compile/test run on my compiler collection and see what comes up.

However, you should be using `_mm_loadu_si128()` rather than `_mm_lddqu_si128()`. `more_testing()` doesn't seem to actually be called, but as we're targeting SSE2 let's use the SSE2 call rather than the SSSE3 one.

**Comment by WayneD** [comment]
The more_testing() routine is a copy of actual code from the real simd file of routines that weren't present in one g++ compiler I tried. So it has to be those ssse3 ones because they were the ones that were causing a failed compilation after a successful configure test.  Also, the routine is marked as inline because when these routines are marked as always-inline, which forces the calling function to be inline.

**Comment by Chainfire** [comment]
If the problematic call on that specific g++ is only `_mm_lddqu_si128()` and it all compiles fine otherwise, we can just replace it with `_mm_loadu_si128()` and avoid the problem altogether.

On all but a handful of the earliest SSSE3 CPUs they are synonymous, and on those where it isn't the performance hit is a single-digit % worst-case.

**Comment by eworm-de** [comment]
Just built version `3.2.1pre1` without issues on Arch Linux.

**Comment by debohman** [comment]
I built `3.2.1pre1` on macOS:

```
rsync  version 3.2.1pre1  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, no atimes, batchfiles, inplace,
    append, ACLs, xattrs, optional protect-args, iconv, symtimes,
    no prealloc, SIMD, asm, openssl-crypto
Checksum list:
    xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none
```
Seems to work.
