### ISSUE TITLE
--backup-dir creates double nested directory

### ISSUE THREAD

**Issue by ynikitenko** [WayneD/rsync#332]
I run this command:

> rsync -avHP --delete-after --backup-dir BACKUP --exclude=/.ys/* /tmp/pytest-of-yaroslav/pytest-5/remote0/ /tmp/pytest-of-yaroslav/pytest-5/local0/

and it creates *BACKUP/BACKUP* instead of just *BACKUP* when I have changed files.
Sorry that this is not an MWE, I didn't debug it thoroughly.

I tried to write it *./BACKUP* or *BACKUP/*, but it didn't change anything.

I'm using Arch Linux, *rsync  version v3.2.4  protocol version 31*.

**Comment by WayneD** [comment]
Read the comments about a relative backup dir: https://download.samba.org/pub/rsync/rsync.1#opt--backup-dir

The only way for rsync to duplicate the backup suffix is if you were affecting the BACKUP dir in the destination, such as doing a `--delete` into the dest w/o excluding the backup dir, since that would delete everything in the backup dir, and thus cause rsync to create things inside that destination dir inside the backup dir.

**Comment by ynikitenko** [comment]
Many thanks! In fact, I read this description several times, but did not understand what it means. Now I understand the meaning of that, but still don't understand the reasoning behind that (and its formulation).

I can not understand the reason, why "that would delete everything in the dest/BACKUP dir, and thus cause rsync to create things inside that destination BACKUP dir inside the requested BACKUP dir".
If BACKUP is not deleted in the end, why create BACKUP/BACKUP? It looks like a pure implementation detail (or at least could something be added to the man about that?)

In the manual the developers write

> Note that if you specify a relative path, the backup directory will be relative to the destination directory, so you probably want to specify either an absolute path or a path that starts with "../". If an rsync daemon is the receiver, the backup dir cannot go outside the module's path hierarchy, so take extra care not to delete it or copy into it.

It looks they (and you) are really discouraging relative destination directories. But it is really hard to understand from these lines why.
For me it even contradicts in spirit to the `--backup` option, which adds files right into the repository without problems.

Is it not self-contradictory if a user removes the BACKUP dir and allows this directory for backups? Should it not be excluded by default?

Thanks again for your clarifications, I think they might well improve the manual.

P.S. I'm writing a wrapper around `rsync` with configuration. For me it is natural that all repository files (including backups) fall exactly into the repository (not anywhere else on the system), this is why I chose a relative path. But now I can fix that, of course.

**Comment by ynikitenko** [comment]
I wonder, was this behaviour always like that? I linked an article from 2020, where it was different (or did they just fix that in their article?)

**Comment by WayneD** [comment]
It's always been like that.

What is generally discouraged is putting the backup dir inside the destination dir, since it can conflict with files from the source dir.  Thus you generally want either an absolute path or one that starts with `../` (when possible).  When not possible, you need to exclude it because the source dir doesn't have any of the backup files that match that in-destination dir.
