### ISSUE TITLE
CVE-2022-29154 question

### ISSUE THREAD

**Issue by mruprich** [WayneD/rsync#345]
Hi Wayne,
I was trying to use the commit https://github.com/WayneD/rsync/commit/b7231c7d02cfb65d291af74ff66e7d8c507ee871 for older version of rsync(3.2.3) and every time it fails on make check because one test always fails - batch-mode. It seems like in this particular case, even good files are rejected right away on the receiver:
```
sending incremental file list
created directory /root/rpmbuild/BUILD/rsync-3.2.3/testtmp/batch-mode/to/missing
./
empty
filelist
nolf
nolf-symlink -> nolf
text
dir/
dir/text
dir/subdir/
dir/subdir/subsubdir/
dir/subdir/subsubdir/etc-ltr-list
dir/subdir/subsubdir2/
dir/subdir/subsubdir2/bin-lt-list
emptydir/

sent 417 bytes  received 268 bytes  1,370.00 bytes/sec
total size is 1,997,355  speedup is 2,915.85 (BATCH ONLY)
Test --read-batch (only): Running: "/root/rpmbuild/BUILD/rsync-3.2.3/rsync  -av --read-batch=BATCH "/root/rpmbuild/BUILD/rsync-3.2.3/testtmp/batch-mode/to""
receiving incremental file list
ERROR: rejecting unrequested file-list name: empty
rsync error: protocol incompatibility (code 2) at flist.c(983) [Receiver=3.2.3]
```
I was not able to figure out yet why this particular test fails but looking at the commit above here - https://github.com/WayneD/rsync/blob/master/flist.c#L996 the condition on check_filter should be '<' instead of '<=' ? No other usage of check_filter goes for '<=' . This fixed the problem with the failed test but I can't figure out whether it actually breaks the fix for the CVE or not.

Thanks and regards,
Michal

**Comment by WayneD** [comment]
Nope, the `<=` code is right because there are only includes in the list and no excludes. A `<` would make the check useless.

The `--read-batch` code should not be adding any args to that implied filter list. It doesn't in 3.2.5 probably because of the huge improvements in batch.c where the BATCH.sh file writes better arg values.  You could consider grabbing that code, however I have also just committed a tweak into the excludes.c file to ensure that `--read-batch` never adds any args.

Also, since you're apparently adapting the code for something older than 3.2.4, the new code won't work without 3.2.4's arg escaping code (that is disabled via `--old-args`). That old-style arg passing disables the extra arg checking because rsync can't know what the remote args truly are if the remote system is interpreting them (the user might have used single quotes, internal spaces for splitting, and even backticks to get args from a remote script). I personally think that just upgrading to 3.2.5 is safer than doing a lot of surgery on an older rsync.

**Comment by rosorio** [comment]
Hi Wayne,
Do you have plans to release rsync 3.2.5 any time soon ?
FreeBSD ports uses tar archives, and moving to github requires some work.
I don't want to do this task just for a couple of days the go back to previous status.

Thanks for your time,
-- rodrigo

**Comment by WayneD** [comment]
It will certainly be soon, but probably something more like a week or so rather than a couple days. If you want to get something out more quickly, perhaps use the 3.2.5pre1 tar file and a patch for the zlib CVE (if you use the included zlib). The other changes since pre1 are pretty minor.  Just be sure to make the version number something that will sort right when the real 3.2.5 comes out.

**Comment by WayneD** [comment]
There have been several fixes to the arg verification code committed this evening.

**Comment by mruprich** [comment]
Thanks Wayne,
yeah I know it would be better to just move to a newer version but unfortunately I need to fix this in a couple of older systems as well so I will do the surgery anyway.

**Comment by WayneD** [comment]
Those patching an older rsync now have the full patch file for 3.2.5 and the upcoming 024bf1d83114d986b1644628f2bc907ccf4e0ef2 & db4f919ebe3dd99a8986d0dc4892ddcda795facf & 6ac2c7b682a427fc80d142e80e73858346a2d024 commits that will be in 3.2.6.

**Comment by rosorio** [comment]
Dear Wayne,

Many thanks for your hard work and dedication.

Regards,
-- rodrigo
