### ISSUE TITLE
Rsync with CVE-2022-29154 patch rejects filename with "[" & "]"

### ISSUE THREAD

**Issue by axzxc1236** [WayneD/rsync#349]
I've always used a command like `rsync server:"/path/to/directory" . --recursive --verbose` to copy file to my local computer, which always worked fine until few days ago, ArchLinux released a rsync version (3.2.4-2) with https://github.com/WayneD/rsync/commit/b7231c7d02cfb65d291af74ff66e7d8c507ee871 applied, through testings I know it now blocks operations with "[" "]" in name when I copy from remote server.

`rsync server:"/path/to/[test]" . --recursive --verbose` now shows "rejecting unrequested file-list name: [test]"

Is this behavior intended? if yes, can you add a flag to disable this protection?

**Comment by matt-h** [comment]
I am getting the same thing as well, although I'm not using `[` or `]`.

Command was just a `rsync -avzz --delete server:/path/to/directory/. /path/to/local/directory/.` and the `rejecting unrequested file-list name: file-1351512-5125125.log` message was listing the first file in the remote directory.

It also displayed this error message: `rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=v3.2.4]`

I'm assuming that it is something to do with that patch that was applied as it worked fine again after going back to 3.2.4-1

**Comment by WayneD** [comment]
Hmm, rsync is interpreting "/path/to/[test]" as a request to transfer up to 3 single-letter filenames with the names `t`, `e`, or `s`.  However, the shell is failing to matc\h any single-letter files and is instead matching the wildcards literally.  I'll look into how best to fix this.  It seems that 3.2.4 onward don't allow the backslash quoting of wildcard chars, which means that you can't ask for '\[test\]' either, which I'll also need to fix.  You can work around the issue by requesting '?test?' or by specifying `--old-args` (until this is fixed).

The second case is rsync not properly translating a trailing dot dir into an include, which I have fixed in my most recent commit.

**Comment by WayneD** [comment]
The latest git source should have all this fixed.
