### ISSUE TITLE
rsync v3.2.5 rejecting unrequested file-list name

### ISSUE THREAD

**Issue by frostschutz** [WayneD/rsync#356]
maybe something similar to #350 

```
$ rsync  --archive --relative --verbose root@server:/etc/. /some/local/path
receiving incremental file list
ERROR: rejecting unrequested file-list name: /etc/logrotate.d
rsync error: protocol incompatibility (code 2) at flist.c(998) [Receiver=v3.2.5]
```

**Comment by WayneD** [comment]
Thanks for the note.  The latest git version has this fixed along with some other related path-cleaning issues.

**Comment by samueloph** [comment]
Hello Wayne,

Is this bug the same as https://github.com/WayneD/rsync/issues/350 and https://github.com/WayneD/rsync/issues/360?

If so, then is it correct to assume the only commit needed to fix it is the following?
https://github.com/WayneD/rsync/commit/a182507bef2d0cd92052b3c5ebaf1d98278e0dad

And do you have any plans on doing a 3.2.6 (or 3.2.5.1) release with this fix anytime soon? 
I'm evaluating whether I should apply the patch or wait for a hotfix release (on Debian's side).

Thank you,

**Comment by WayneD** [comment]
It's similar, but I wouldn't pick and choose commits as it is easier to view all the v3.2.5 changes as a single patch (since the whole release is bug fixes & security fixes). You can look at the official gzip file or run `git diff v3.2.4 v3.2.5`.

So, viewing all the changes as a whole, you want:
* all changes from zlib/inflate.c (ZLIB fix)
* all changes from exclude.c (args)
* all changes from flist.c (args)
* all changes from io.c (args)
* all changes from main.c (args)
* all changes from options.c (args & the `--trust-sender` option that gives the user a way to disable the new checking if it goes wrong)
* maybe the changes from receiver.c (a daemon fix for daemon filters to get the dir flags right)
* maybe the changes from checksum.c & usage.c (it ensures that the xxhash shared lib is really 8.0 and disables the XXH3 hashes if it is not)

v3.2.6 is in the works, and so far you want (`git diff v3.2.5`):
* all changes in checksum.c (MD4, but optional if openssl is being used)
* all changes in exclude.c (args)
* all changes in options.c (args related to improving --relative with a remote arg that uses a tilde but the tilde expansion doesn't factor into the directories that are a part of the transfer due to a "/./" in the path)

**Comment by thesamesam** [comment]
@WayneD Is your recommendation for distros to backport the 3.2.6 patches or just wait for 3.2.6 (any rough planned timeline for that if so)?

**Comment by WayneD** [comment]
I'm planning to release 3.2.6 in the next few days.

**Comment by papoteur-mga** [comment]
Some news about the new release?

**Comment by ESIC-DA** [comment]
Thanks for all your hard work on rsync over the years!

+1 on knowing when this will be released...seems like the bug(s) from 3.2.5 were backported to the 3.1.3 in EL8 (RHEL8 / Rocky 8 / etc) and so our debian repo/mirror is now broken as well.

**Comment by thesamesam** [comment]
3.2.6 was released today.

**Comment by samueloph** [comment]
I believe 3.2.6 is still triggering this issue (at least in some cases), as confirmed by:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019561

Some Debian folks also confirmed that they're still experienced the same issue reported here with 3.2.6:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018296

And there's also this bug report on RedHat's side (where Fedora users confirm the issue for 3.2.5), where there might be confirmation from them that 3.2.6 still has the issue soon:
https://bugzilla.redhat.com/show_bug.cgi?id=2123815

I don't have permission to reopen this issue so I'm tagging @WayneD so he can have a look.

**Comment by bootc** [comment]
FWIW I'm the reporter of Debian bug 1018296 and can confirm it still occurs with [3.2.6-1](https://packages.debian.org/source/unstable/rsync).

**Comment by WayneD** [comment]
Sigh, nobody can bother to test for a month of pre-release.  How marvelous.

**Comment by WayneD** [comment]
Not seeing any bugs with any of the listed reports as of 3.2.6.

**Comment by WayneD** [comment]
Seems to be a bug with --no-inc-recurse.

**Comment by WayneD** [comment]
This commit should fix things up for you: 950730313de994d191ba2d5be575e97690b355e8

**Comment by frostschutz** [comment]
3.2.6 works fine for me. Thank you for the fix. :+1:

**Comment by samueloph** [comment]
For Debian users: I've uploaded a few important fixes (including this one)[0] to Debian unstable as version `3.2.6-4`, and it will reach testing in a few days.

[0] Commits ported were:
https://github.com/WayneD/rsync/commit/950730313de994d191ba2d5be575e97690b355e8
https://github.com/WayneD/rsync/commit/71c2b5d0e386b845fb2f4d427568451f098008ff
https://github.com/WayneD/rsync/commit/464555ea923b32f3504678d05bc7de9205e5c8da
