### ISSUE TITLE
--mkpath doesn't preserve ownership/modes

### ISSUE THREAD

**Issue by mjb512** [WayneD/rsync#388]
Contrary to expectation, `--mkpath` results in the leading elements being created with default permissions instead of ones matching the remote side, regardless of other permission-preserving rsync options.

I suspect preserving ownership's going to be a non-trivial job, if at all possible, so I feel a caveat in the man page might be the correct  course of action to at least document the discontinuity.

**Comment by noahbkim** [comment]
Hi, hoping to relitigate this issue for the usecase where we can't use `--relative` e.g. because the origin path is a temporary file and the target path is in some nested directory that may not exist yet. I'm wondering:

- if `--mkpath` could at least respect `--chmod`,
- if you'd accept a PR or patch implementing this
- if there are any workarounds in the meantime
