### ISSUE TITLE
rsync does not terminate when target disk is full

### ISSUE THREAD

**Issue by Richie765** [WayneD/rsync#71]
I'm copying a set of large files to a disk, when the disk is full, rsync does not terminate. When I stop rsync, it shows a "No space left" error. Here is an example of the output. Rsync was ran when the disk was already full from a previous run. 

```
[root@backup]# rsync -av /data/source/ /mnt/bck/dest/
sending incremental file list
dump/
dump/2020_07_17.tgz
dump/2020_07_13.tgz
dump/2020_07_15.tgz
dump/2020_07_17.tgz
dump/2020_06_29.tgz
dump/2020_05_06.tgz
dump/2020_07_10.tgz
dump/2020_07_13.tgz
^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(688) [sender=3.2.2]
rsync: [receiver] write failed on "/mnt/bck/dest/2020_07_17.tgz": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(378) [receiver=3.2.2]
```

As you see, the error shows the first file that supposedly was copied. Afterwards, none of the listed files that were supposed to have been copied even exist on the destination disk. It has been ran several hours like this without any error until it is stopped. Also tried as non-root user with same effect.

The same issue seems to arise when copying to a destination without writing permissions. When stopping rsync:
```
rsync: mkstemp "/mnt/bck/dest/dump/.2020_07_17.tgz.C2GxbN" failed: Permission denied (13)
```
rsync 3.2.2

EDIT: Compiled latest rsync and tried again: same result.

**Comment by WayneD** [comment]
Yeah, that's a side effect of the pipelined nature of the rsync protocol. The pipes get filled up with data of future requests so much so that any remote errors take quite a few files to migrate through the backlog. You can work around the issue by using `--msgs2stderr` when possible (as long as the receiving side has a stderr that is sent to you).  It's also sad that the default for a local transfer was made to be a "push" which makes the receiver behave as through it's a remote process.

I'm already looking into a big rewrite of the protocol that would attempt to always keep some available space for messages, but that will require a large architecture change since the process doing the sending is separate from the process doing the receiving, and they don't currently have a way to figure out how full the sender's input buffer is (especially since it can only read the input buffer after it finishes sending all the data for the prior file, since the buffer fills up with checksum data and/or file-send requests).

Since this problem is inherent in the way rsync works and there is a work-around fix, I'm closing this bug.  A future rsync 4.0 will hopefully not have this issue.

**Comment by WayneD** [comment]
Actually, I had another idea for how to improve this.  I'm changing the default for outputting errors to use stderr for a local & remote-shell transfer, which means that the newest version should have this fixed for normal copies without having to resort to using `--msgs2stderr` (and without making info messages go to stderr too).

**Comment by Richie765** [comment]
Ok, great! I've just added some disks to my backup set so I won't run out of disk space for a while, but by the time one of them gets full again it's great to have this working well again! Thanks!

**Comment by varac** [comment]
Any updates on this ?
