### ISSUE TITLE
Patch hfs-compression.diff errors

### ISSUE THREAD

**Issue by TonyTTTT** [WayneD/rsync#79]
Patch hfs-compression.diff errors
macOS 10.15.6

attrs.c:274:1: error: unknown type name '$$$ERROR$$$'
$$$ERROR$$$ the old patch needs reworking since rsync_xal_get() has tota...
^
xattrs.c:274:16: error: expected ';' after top level declarator
$$$ERROR$$$ the old patch needs reworking since rsync_xal_get() has tota...
               ^
               ;
xattrs.c:1365:2: error: #endif without #if

**Comment by WayneD** [comment]
Yup, nobody with a Mac has submitted any fixes yet.  I've had one person suggest that they might supply some, but no word yet.  I'll just be removing it if it doesn't get some changes before too long.

**Comment by TonyTTTT** [comment]
With APFS, I don't need it, so just I compiled without the patch.
(IIRC. Mike Bombitch originally wrote the patch for his CCCloner program)
I'll send Mike an email, maybe he'll send in a fix.

**Comment by emclain** [comment]
`$$$ERROR$$$ the old patch needs reworking since rsync_xal_get() has totally changed!`

I was looking at this and I'm kind of puzzled by this comment.  Looking at the blame for xattrs.c, I don't see any drastic changes to rsync_xal_get().  Or is it this change?  https://github.com/WayneD/rsync/commit/6eb71beaffb365c8f3b3d0db3ab7123026ee423e

Do you know what concern this comment was referring to?

**Comment by emclain** [comment]
There is a stray `#endif` in the patch, but once that's removed it applies and builds cleanly.   (Whether it works... is another question).

**Comment by WayneD** [comment]
Note that rsync patches is best discussed on the rsync-patches project, which has a bug open on this issue.
https://github.com/WayneD/rsync-patches/issues/1
