### ISSUE TITLE
3.2.3 rsync spurious "is newer" messages

### ISSUE THREAD

**Issue by franke-hub** [WayneD/rsync#98]
When transferring files into a 3.2.3 rsync, every file gets an "is newer" message. Between two 3.2.3 clients, all files are displayed as "is newer" in either direction with options -u and --info=skip specified. When file times are identical, there should be no "is newer" warning.

When both the source and the destination are synchronized with identical file content and modification times:
Source 3.1.2 => Dest 3.2.3, all files are "is newer" (-u set)
Source 3.2.3 => Dest 3.1.2, no "is newer" message (-u set) 
Source 3.2.3 => Dest 3.2.3, all files are "is newer" (-u set)
There is no message unless both -u and --info=skip are specified.

The full (failing) command line: rsync -aiOuz --info=skip --del --max-delete=0 . target-machine:tmp
The full (working) command line: rsync -aiOz --info=skip --del --max-delete=0 . target-machine:tmp

**Comment by WayneD** [comment]
Thanks for pointing that out.  I've fixed the issue in git & have added a test to ensure it doesn't happen again.

**Comment by idallen** [comment]
Alas, the latest Ubuntu 22.04.1 LTS (Long Term Support release) has adopted this two-year-old 3.2.3 version of rsync, and Ubuntu refuses to adopt a more recent, fixed version because they think the issue is "minor", so everyone using Ubuntu LTS is  stuck with this spurious "is newer" problem for at least another two years:  https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/1965076

**Comment by WayneD** [comment]
The fix was very simple: fd6839b7464f53afb4cf016e4b4f6d2c477eb8d8

**Comment by panlinux** [comment]
Jammy will get an update, see https://bugs.launchpad.net/ubuntu/+source/rsync/+bug/1965076
